#Build stage

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY ["Alterian_POS.csproj", "./"]
RUN dotnet restore "Alterian_POS.csproj"

COPY . .

RUN dotnet publish "Alterian_POS.csproj" \
    --configuration Release \
    --output /app/publish \
    --no-restore


# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080

EXPOSE 8080

ENTRYPOINT ["dotnet", "Alterian_POS.dll"]